### ISSUE TITLE
反馈BUG。在标签页的显示文章列表，如果有多页，最后一页不显示

### ISSUE THREAD

**Issue by ghost** [zjhch123/solo-skin-amaze#1]
问题详细描述：
在标签页，点击一个文章较多的标签，例如：https://www.gwt.fun/tags/%E5%89%91%E6%8C%87Offer，在页数超过1时，会不显示最后一页的页码。url变成：https://www.gwt.fun/tags/%E5%89%91%E6%8C%87Offer?p=   ，不清楚首页文章列表最后一页是否显示。
错误位置：
article-list.ftl 页面，74行  ${paginationNextPageNum}参数在最后一页显示为空，目前原因不详
临时解决方案;
将 ${paginationNextPageNum}参数修改为${paginationCurrentPageNum+1}

**Comment by 88250** [comment]
最后一页用这个变量 `paginationLastPageNum`，具体可参考 [Solo 皮肤开发指南](https://hacpai.com/article/1493814851007)。

**Comment by zjhch123** [comment]
> 最后一页用这个变量 `paginationLastPageNum`，具体可参考 [Solo 皮肤开发指南](https://hacpai.com/article/1493814851007)。

我这边是只显示上一页下一页的哈，不直接显示最后一页页码的

**Comment by zjhch123** [comment]
已修复，感谢 @GaoWentian @88250
