### ISSUE TITLE
solo 3.0.0 皮肤升级

### ISSUE THREAD

**Issue by Vanessa219** [zjhch123/solo-skin-amaze#2]
相关修改点参见 https://github.com/b3log/solo-skins/commit/4b5e8d897dc2738f529596354b1150e81fa39869

相关 issue： https://github.com/b3log/solo/issues/12645

**Comment by 88250** [comment]
https://github.com/b3log/solo/issues/12704

**Comment by zjhch123** [comment]
最近比较忙…明天抽空更新一下，顺便也更新一下自己的博客版本

**Comment by 88250** [comment]
@zjhch123 感谢感谢。对了，升级的时候记得看一下每个版本的迁移步骤，还有升级前一定要备份数据 🙏

**Comment by zjhch123** [comment]
目前已更新~ 支持solo 3.2.0~ @Vanessa219 @88250 
[preview](https://blog.hduzplus.xyz/)

**Comment by 88250** [comment]
@zjhch123 收到，辛苦了 ❤️

**Comment by 88250** [comment]
对了，可以在 GitHub 上 release 一下，类似[这里](https://github.com/b3log/solo-skins/releases)，版本号对应 Solo 的版本，这样方便用户选择。

**Comment by zjhch123** [comment]
@88250 收到，感谢提醒~

**Comment by Vanessa219** [comment]
进去还是 500

**Comment by qichuangguo** [comment]
[ERROR]-[2019-03-13 14:44:09]-[org.b3log.latke.Latkes:756]: Read skin [solo-skin-amaze-master]'s  configuration failed: null
[ERROR]-[2019-03-13 14:44:09]-[org.b3log.latke.Latkes:756]: Read skin [solo-skin-amaze-master]'s  configuration failed: null
[INFO ]-[2019-03-13 14:44:12]-[org.b3log.solo.SoloServletListener:127]: Solo is running
[INFO ]-[2019-03-13 14:44:17]-[org.b3log.solo.util.Markdowns:128]: [marked] is not available, uses built-in [flexmark] for markdown processing. Please read FAQ section in user guide (https://hacpai.com/article/1492881378588) for more details.
[ERROR]-[2019-03-13 14:44:18]-[org.b3log.solo.util.Skins:96]: Gets console template [index.ftl] failed
freemarker.template.TemplateNotFoundException: Template not found for name "index.ftl".
The name was interpreted by this TemplateLoader: WebappTemplateLoader(subdirPath="/", servletContext={contextPath="", displayName="/"}).

**Comment by zjhch123** [comment]
@Vanessa219 @qichuangguo 已更新修复。实在抱歉，之前没有验证未登录的情况
